
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Get the latest publisher - don't run the batch script but run the line directly
          args: curl -L https://github.com/costateixeira/publisher/raw/main/publisher.jar -o ./publisher.jar --create-dirs

      - name: Check out IG
        uses: actions/checkout@master
        with:
          repository: costateixeira/core
          path: './core'

      - name: Check out history
        uses: actions/checkout@master
        with:
          repository: HL7/fhir-ig-history-template
          path: './history-template'

      - name: Check out current publication folder
        uses: actions/checkout@master
        with:
          repository: medigree/current-publication
          path: './webroot'

      - name: Check out IG registry
        uses: actions/checkout@master
        with:
          repository: FHIR/ig-registry
          path: './ig-registry'

      - name: First, build the IG normally
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar ./publisher.jar publisher -ig core


      - name: List files
        run: |
          pwd
          ls ./webroot

#      - name: Then, run the -go-publish for preparing the publication
#        uses: docker://hl7fhir/ig-publisher-base:latest
#        with:
#          args: curl -L https://github.com/costateixeira/publisher/raw/main/publisher.jar -o ./publisher.jar

      - name: Then, run the -go-publish for preparing the publication
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar publisher.jar -go-publish -source core -destination webroot -registry ./ig-registry/fhir-ig-list.json -history ./history-template



#      - name: Build Implementation Guide with the -go-publish for preparing the publication
#        run: |
#          docker run \
#            -v $(pwd):/home/publisher/ig \
#            hl7fhir/ig-publisher-base:latest \
#            sh -c "java -jar publisher.jar -go-publish -source ./core -destination $(pwd)/webroot -registry ./ig-registry/fhir-ig-list.json -history ./history-template"


#      - name: Deploy webroot to gh-pages
#        uses: JamesIves/github-pages-deploy-action@v4
##        if: ${{ steps.branch-name.outputs.is_default }} == 'true'
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: ./webroot # The folder the action should deploy.
#          commit-message: Deploy main branch
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webroot

