
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#      - name: Create gh-pages branch if it doesn't exist
#        uses: christopherdavenport/create-ghpages-ifnotexists@v1    

      - name: Check out history
        uses: actions/checkout@master
        with:
          repository: HL7/fhir-ig-history-template
          
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: FHIR/ig-registry

      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Get the latest publisher - don't run the batch script but run the line directly
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs

      - name: Hello world
        run: |
          ls

      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Run the publisher - don't run the batch script but run the line directly
          args: java -jar ./input-cache/publisher.jar publisher -ig .

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.3
