
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          # Get the latest publisher - don't run the batch script but run the line directly
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./publisher.jar --create-dirs

      - name: Check out IG
        uses: actions/checkout@master
        with:
          repository: costateixeira/core
          path: './core'

#      - name: Create gh-pages branch if it doesn't exist
#        uses: christopherdavenport/create-ghpages-ifnotexists@v1    

      - name: Check out history
        uses: actions/checkout@master
        with:
          repository: HL7/fhir-ig-history-template
          path: './history-template'

      - name: Check out current publication folder
        uses: actions/checkout@master
        with:
          repository: medigree/current-publication
          path: './webroot'

      - name: List
        run: |
          ls `pwd`/webroot



#      - name: List
#        run: |
#          cp webroot/core/package-list.json core

      - name: Check out IG registry
        uses: actions/checkout@master
        with:
          repository: FHIR/ig-registry
          path: './ig-registry'


      - name: List
        run: |
          ls

      - name: First, build the IG
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar ./publisher.jar publisher -ig core


      - name: Then, run the -go-publish
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar publisher.jar -go-publish -source ./core -destination `pwd`/webroot -registry ./ig-registry/fhir-ig-list.json -history ./history-template

#      - name: Get branch names
#        id: branch-name
#        uses: tj-actions/branch-names@v4.3

      - name: List
        run: |
          ls webroot
          

      - name: Deploy main
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ steps.branch-name.outputs.is_default }} == 'true'
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./webroot # The folder the action should deploy.
          commit-message: Deploy main branch
