name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hl7fhir/ig-publisher-base:latest

    steps:
      - name: Update the image to the latest publisher
        run: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./publisher.jar --create-dirs

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Sushi version
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: npm install -g fsh-sushi@3.3.3 

#      - name: Install specific version of fsh-sushi inside the container and update PATH
#        run: |
#          npm install -g fsh-sushi@3.3.3
#          echo "$(npm bin -g)" >> $GITHUB_PATH

#      - name: Replace container's SUSHI with the installed version
#        run: cp $(npm bin -g)/sushi /home/publisher/.node/bin/sushi

      - name: Check sushi version inside the container
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: sushi -v

#      - name: Check updated sushi version in container
#        run: /home/publisher/.node/bin/sushi -v

      - name: Checkout medigree/core to ./core
        uses: actions/checkout@v2
        with:
          repository: medigree/core
          path: core

      - name: Checkout HL7/fhir-ig-history-template to ./history-template
        uses: actions/checkout@v2
        with:
          repository: HL7/fhir-ig-history-template
          path: history-template

      - name: Checkout medigree/current-publication to ./webroot
        uses: actions/checkout@v2
        with:
          repository: medigree/current-publication
          path: webroot

      - name: Checkout FHIR/ig-registry to ./ig-registry
        uses: actions/checkout@v2
        with:
          repository: FHIR/ig-registry
          path: ig-registry

      - name: Create folder
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          entrypoint: /bin/sh
          args: -c "mkdir -p ./fhir-package-cache && chown 1001:127 ./fhir-package-cache"

      - name: Run publisher command
        run: java -jar ./publisher.jar publisher -ig core -package-cache-folder ./fhir-package-cache

      - name: Run publisher command for publishing release
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -Dfile.encoding=UTF-8 -jar publisher.jar -go-publish -package-cache-folder ./fhir-package-cache -source core -web $(pwd)/webroot -registry ./ig-registry/fhir-ig-list.json -history ./history-template -templates $(pwd)/webroot/templates

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webroot
